;(function($){
	$(function(){
		$('.nav-bar').gdscarousel({
			imglist:['img/banner1.jpg','img/banner2.jpg','img/banner3.jpg','img/banner4.jpg','img/banner5.jpg','img/banner6.jpg'],
			page:'center',
			type:'fade',
			showButton:false,
			width:1370,
			height:491
		});
		$('.scroll-A').gdscarousel({
			imglist:['img/r1.jpg','img/r2.jpg','img/r3.jpg'],
			page:'center',
			type:'fade',
			showButton:true,
			width:188,
			height:142,
			autoPlay:false
		});
	});
})(jQuery);
